### ISSUE TITLE
missing dusty buns and tagline

### ISSUE THREAD

**Issue by Alexg1021** [geekwise-kao-thao/dustybuns#1]
missing db title and tagline in banner section

**Comment by geekwise-kao-thao** [comment]
not sure what you are asking. could you please clarify?

**Comment by geekwise-kao-thao** [comment]
it's on there now, thanks

I appreciate these issues because they help me become more detail oriented.

**Comment by geekwise-kao-thao** [comment]
is there still an issue for this part?

**Comment by Alexg1021** [comment]
Issue resolved :+1:
