### ISSUE TITLE
button on http://geekwise-kao-thao.github.io/dustybuns/sf_lunch_box.html

### ISSUE THREAD

**Issue by Alexg1021** [geekwise-kao-thao/dustybuns#11]
![screen shot 2016-03-30 at 5 06 06 pm](https://cloud.githubusercontent.com/assets/11038686/14161606/fb67e314-f699-11e5-99e9-3ba52058f8fc.png)

**Comment by geekwise-kao-thao** [comment]
fixed

**Comment by geekwise-kao-thao** [comment]
per alex, closing issue
