### ISSUE TITLE
linking

### ISSUE THREAD

**Issue by haniali1234** [geekwise-kao-thao/dustybuns#12]
page: Fresno Bus
issue: Check out the side widget on the original site and see how there is a hover and the email is linked
photo: 
![screen shot 2016-03-31 at 8 25 38 am](https://cloud.githubusercontent.com/assets/11038599/14181097/81c90476-f71a-11e5-886b-2a4315f85aee.png)

**Comment by geekwise-kao-thao** [comment]
added links, hover included

**Comment by haniali1234** [comment]
change color when you hover

**Comment by geekwise-kao-thao** [comment]
color changes when hovering now.
