### ISSUE TITLE
Extra lines

### ISSUE THREAD

**Issue by haniali1234** [geekwise-kao-thao/dustybuns#13]
page: Contact us
issue : extra line
photo:
![screen shot 2016-03-31 at 8 30 03 am](https://cloud.githubusercontent.com/assets/11038599/14181218/f2225e02-f71a-11e5-98b3-fb7affd96da3.png)

**Comment by geekwise-kao-thao** [comment]
line deleted

**Comment by haniali1234** [comment]
page: Contact us
issue : No map
photo:
![screen shot 2016-03-31 at 9 26 52 am](https://cloud.githubusercontent.com/assets/11038599/14182999/c98b9050-f722-11e5-98be-21bba389fe31.png)
