### ISSUE TITLE
home page background image height issue

### ISSUE THREAD

**Issue by Alexg1021** [geekwise-kao-thao/dustybuns#3]
the background image isn't covering 100% of the screen like it does on the db site
![kao-db-home](https://cloud.githubusercontent.com/assets/11038686/13933110/c8c88fb8-ef68-11e5-9495-2d6d321cbb73.png)

**Comment by geekwise-kao-thao** [comment]
thank you,

use height:100vh as you suggested and it fixed the issue

**Comment by Alexg1021** [comment]
Looks good!
