### ISSUE TITLE
Missing the hovor

### ISSUE THREAD

**Issue by haniali1234** [geekwise-kao-thao/dustybuns#4]
page: home
issue: navbar
photo:
![screen shot 2016-03-21 at 2 46 41 pm](https://cloud.githubusercontent.com/assets/11038599/13935290/d41f4fea-ef73-11e5-9e2b-3901482e7a3a.png)

**Comment by geekwise-kao-thao** [comment]
thank you,

corrected issue.  had to add transition .5s to control hover appearing and disappearing
