### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by haniali1234** [geekwise-kao-thao/dustybuns#7]
page: SF
Issue: names should be on top.
Photo:
![screen shot 2016-03-28 at 10 18 22 am](https://cloud.githubusercontent.com/assets/11038599/14084336/257752ec-f4cf-11e5-98d6-39981892f551.png)

**Comment by geekwise-kao-thao** [comment]
fixed (see photo below). also, if you noticed, the names when compared to it's bootstrap icons are not aligned and one of them is missing.  so, i fixed that.  if you don't like it, i can make it look like the original (broken).

![image](https://cloud.githubusercontent.com/assets/17086853/14087621/c66690ea-f4df-11e5-8f46-c8413659f9c5.png)
