### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by haniali1234** [geekwise-kao-thao/dustybuns#8]
page: All
issue: font on SAFARI  Browser
Photo:
![screen shot 2016-03-28 at 12 44 25 pm](https://cloud.githubusercontent.com/assets/11038599/14088236/289aa280-f4e3-11e5-84b1-9d528275c150.png)

**Comment by haniali1234** [comment]
I would say, try and get the font from google and make it as smilier as possible and link it.

**Comment by geekwise-kao-thao** [comment]
I think you have the wrong guy

Kao

I would say, try and get the font from google and make it as smilier as
possible and link it.

**Comment by geekwise-kao-thao** [comment]
this is what mine looks like.  i know you have the wrong guy

![image](https://cloud.githubusercontent.com/assets/17086853/14089082/d1d4e76c-f4e7-11e5-8724-6f3b35c1fceb.png)

**Comment by geekwise-kao-thao** [comment]
the one you sent me looks like it belongs to Alonzo

**Comment by haniali1234** [comment]
you have windows how did you test it?
this is what your site looks like on safari.
![screen shot 2016-03-28 at 3 11 45 pm](https://cloud.githubusercontent.com/assets/11038599/14091869/94eaebac-f4f7-11e5-874d-da71f4aa5523.png)

**Comment by geekwise-kao-thao** [comment]
linked it to google fonts.  i tested on my devices (phone and tablet) in chrome only.  is safari mac?  can you check it again?

**Comment by haniali1234** [comment]
yes. 
Nice!.
![screen shot 2016-03-28 at 4 18 43 pm](https://cloud.githubusercontent.com/assets/11038599/14093172/c689689c-f500-11e5-9101-6f2834b2e803.png)

**Comment by haniali1234** [comment]
Page:  All
issue: mobile view needs to be lined up
Photo:   Sorry should say padding top
![screen shot 2016-03-28 at 7 17 47 pm](https://cloud.githubusercontent.com/assets/11038599/14096052/9a214c7e-f51a-11e5-9a35-435477068e49.png)

Page: contact us
issue: they need to be linked
photo: 
![screen shot 2016-03-28 at 7 14 55 pm](https://cloud.githubusercontent.com/assets/11038599/14096086/d01e5790-f51a-11e5-87d2-485aaf82cd10.png)

page: All
issue: footer logo need to be linked
photo:
![screen shot 2016-03-28 at 7 16 22 pm](https://cloud.githubusercontent.com/assets/11038599/14096099/e1c2100e-f51a-11e5-80e6-c34335b2882d.png)

Page: SF and carrers
issue: in mobile view. San Francisco needs to be centered all the time.
photo: 
![screen shot 2016-03-28 at 7 19 11 pm](https://cloud.githubusercontent.com/assets/11038599/14096118/06ac81e2-f51b-11e5-88a2-83a3f4a20177.png)

Page: about us
issue: spacing
photo:
![screen shot 2016-03-28 at 7 12 02 pm](https://cloud.githubusercontent.com/assets/11038599/14096133/2ca7d770-f51b-11e5-8b7b-ca05ba322cba.png)

Page: SF Lunch Box Order Form and Fresno Lunch Box Order Forms
issue: missing a Pick up
photo:
![screen shot 2016-03-28 at 7 29 13 pm](https://cloud.githubusercontent.com/assets/11038599/14096192/8de349ac-f51b-11e5-9a89-c734bfeb708d.png)

page : Catering / Special Events
issue: spacing
photo: 
![screen shot 2016-03-28 at 7 32 10 pm](https://cloud.githubusercontent.com/assets/11038599/14096235/e74a7c72-f51b-11e5-908a-1a277f3ac0bd.png)

**Comment by haniali1234** [comment]
page: about us
issue: the arrows should go under the navbar
photo:
![screen shot 2016-03-28 at 7 37 28 pm](https://cloud.githubusercontent.com/assets/11038599/14096336/99db871e-f51c-11e5-9aa8-1954115dfa10.png)

**Comment by geekwise-kao-thao** [comment]
thank you.

fixed all issues except the arrow on the about page in the slider.

**Comment by haniali1234** [comment]
Page: home and contact us
 issue: the email isnt linked

 Page: contact us
 issue: the social media and email are not linked

 Page: All
 issue: All footer logo need to be linked to the home page.

**Comment by geekwise-kao-thao** [comment]
Page: home and contact us
issue: the email isnt linked

their email is not linked, but if you hover over the email address it shows the "mailto:#" or i can link it to google.com because the first time i clicked on theirs it took me to google.com home page.

Page: contact us
issue: the social media and email are not linked

social media icons in the their website are not linked, just the words.

Page: All
issue: All footer logo need to be linked to the home page.

fixed

thanks for the issues
